#logging.level.org.apache.coyote.http11: debug
server:
  port: 8086
  servlet:
    encoding:
      charset: UTF-8
    session:
      tracking-modes: cookie
      timeout: 1800
  error:
    whitelabel:
      enabled: false
    include-exception: true
    include-message: always
    include-stacktrace: on_param
    include-binding-errors: on_param

spring:
  output:
    ansi:
      enabled: ALWAYS
  messages:
    basename: messages,errors
