#logging.level.org.apache.coyote.http11: debug
server:
  port: 8086
  servlet:
    encoding:
      charset: UTF-8
    session:
      tracking-modes: cookie
      timeout: 60

spring:
  output:
    ansi:
      enabled: ALWAYS
  messages:
    basename: messages,errors



